SELECT A.AUTHOR_ID,AUTHOR_NAME,CATEGORY,SUM(SALES * PRICE) AS TOTAL_SALES
from BOOK A join AUTHOR B on A.AUTHOR_ID=B.AUTHOR_ID 
join BOOK_SALES C on A.BOOK_ID =C.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY,AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC