SELECT A.CAR_ID, A.CAR_TYPE, TRUNCATE(DAILY_FEE * 30 * (1 - (discount_rate / 100)), 0) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B 
  ON A.CAR_TYPE = B.CAR_TYPE
WHERE DURATION_TYPE = '30일 이상'
  AND TRUNCATE(DAILY_FEE * 30 * (1 - (discount_rate / 100)), 0) >= 500000 
  AND TRUNCATE(DAILY_FEE * 30 * (1 - (discount_rate / 100)), 0) <= 2000000 
  AND CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
  )
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;