SELECT A.USER_ID, A.NICKNAME,B.TOTAL_SALES
FROM USED_GOODS_USER AS A JOIN (
    SELECT WRITER_ID,SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE)>=700000
    ) AS B ON A.USER_ID=B.WRITER_ID
ORDER BY  TOTAL_SALES


# SELECT A.USER_ID, A.NICKNAME, SUM(PRICE) AS TOTAL_SALES
# FROM USED_GOODS_USER AS A JOIN USED_GOODS_BOARD AS B
#     ON A.USER_ID=B.WRITER_ID
# WHERE STATUS = 'DONE'
# GROUP BY A.USER_ID, A.NICKNAME
# HAVING TOTAL_SALES >=700000
# ORDER BY  TOTAL_SALES