select YEAR(A.DIFFERENTIATION_DATE)AS YEAR,
B.MAX_SIZE-A.SIZE_OF_COLONY AS YEAR_DEV,
A.ID
from ECOLI_DATA AS A
Join (select YEAR(DIFFERENTIATION_DATE) AS YEAR,
     MAX(SIZE_OF_COLONY) AS MAX_SIZE
     from ECOLI_DATA 
     GROUP BY YEAR(DIFFERENTIATION_DATE)
     ) as B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;