select ID,FISH_NAME,LENGTH
from FISH_NAME_INFO
join  FISH_INFO  on FISH_NAME_INFO.FISH_TYPE=FISH_INFO.FISH_TYPE
where  (LENGTH,FISH_NAME_INFO.FISH_TYPE) in
( select max(LENGTH), FISH_TYPE from FISH_INFO group by FISH_TYPE)
order by ID
